[package]
name = "flux_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.14.0"
text-size = "1.1.1"
cstree = { version = "0.12.0", features = ["multi_threaded_interning"] }

flux_diagnostics = { path = "../flux_diagnostics" }
flux_util = { path = "../flux_util" }
