[package]
name = "flux_util"
version = "0.1.0"
edition = "2021"

[dependencies]
lasso = { version = "0.7.2", features = ["multi-threaded"] }
cstree = { version = "0.12.0", features = ["multi_threaded_interning"] }
text-size = "1.1.1"
