[package]
name = "flux-mir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flux-error = { path = "../flux-error" }
smol_str = "0.1.21"
indexmap = "1.7.0"
