[package]
name = "flux_span"
version = "0.1.0"
edition = "2021"

[dependencies]
text-size = "1.1.1"
cstree = { version = "0.12.0", features = ["multi_threaded_interning"] }
lasso = { version = "0.7.2", features = ["multi-threaded"] }

