[package]
name = "flux-error"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text-size = "1.0.0"
ariadne = "0.1.5"
smol_str = "0.1.23"
flux-span = { path = "../flux-span" }
