[package]
name = "flux"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.15.0"
lasso = { version = "0.6.0", features = ["multi-threaded"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
itertools = "0.10.5"

flux_diagnostics = { path = "../flux_diagnostics" }
flux_parser = { path = "../flux_parser" }
flux_hir = { path = "../flux_hir" }
flux_span = { path = "../flux_span" }
