[package]
name = "flux"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.15.0"
lasso = { version = "0.6.0", features = ["multi-threaded"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tracing-tree = "0.2.2"
itertools = "0.10.5"
la-arena = "0.3.0"
toml = "0.7.3"
serde = { version = "1.0.159", features = ["derive"] }
clap = { version = "4.2.5", default-features = true, features = ["std", "derive"] }
pretty = "0.12.1"

flux_diagnostics = { path = "../flux_diagnostics" }
# flux_parser = { path = "../flux_parser" }
flux_hir = { path = "../flux_hir" }
# flux_mir = { path = "../flux_mir" }
# flux_typesystem = { path = "../flux_typesystem" }
# flux_span = { path = "../flux_span" }

# [dev-dependencies]
# flux_proc_macros = { path = "../flux_proc_macros" }