[package]
name = "pi-hir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi-syntax = { path = "../pi-syntax" }
smol_str = "0.1.21"
la-arena = "0.2.0"
