[package]
name = "pi-codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi-ast = { path = "../pi-ast" }
llvm-sys = "130.0.1"
