[package]
name = "flux_diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4.0"
text-size = "1.1.1"

flux_span = { path = "../flux_span" }
salsa = { path = "../../lib/salsa" }