[package]
name = "flux_syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
cstree = { version = "0.12.0", features = ["multi_threaded_interning"] }
text-size = "1.1.1"

flux_lexer = { path = "../flux_lexer" }
