[package]
name = "pi-mir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi-ast = { path = "../pi-ast" }
pi-error = { path = "../pi-error" }
smol_str = "0.1.21"
indexmap = "1.8.1"
