[package]
name = "pi-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pi-ast = { path = "../pi-ast" }
nom = "7.0"
smol_str = "0.1.21"