[package]
name = "flux_typesystem"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.37"
paste = "1.0.15"

flux_proc_macros = { path = "../flux_proc_macros" }
flux_diagnostics = { path = "../flux_diagnostics" }
flux_util = { path = "../flux_util" }
flux_id = { path = "../flux_id" }
