[package]
name = "flux_mir"
version = "0.1.0"
edition = "2021"

[dependencies]
la-arena = "0.3.0"
lasso = "0.6.0"

flux_hir = { path = "../flux_hir" }
flux_span = { path = "../flux_span" }

# The only thing that should be used here is `ice`
flux_diagnostics = { path = "../flux_diagnostics" }